services:
  host-a:
    build: ./ansible/docker/sshd-host
    container_name: host-a
    privileged: true
    networks:
      - observability
    ports:
      - "2222:22"
    volumes:
      - ./ssh/authorized_keys:/root/.ssh/authorized_keys:ro
  
  host-b:
    build: ./ansible/docker/sshd-host
    container_name: host-b
    privileged: true
    networks:
      - observability
    ports:
      - "2223:22"
    volumes:
      - ./ssh/authorized_keys:/root/.ssh/authorized_keys:ro  
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - observability      

networks:
  observability:
    name: observability

volumes:
  prometheus-data:
  grafana-data:
