all:
    children:
      monitored:
        hosts:
          host-a:
            ansible_host: 127.0.0.1
            ansible_port: 2222
            ansible_user: root
          host-b:
            ansible_host: 127.0.0.1
            ansible_port: 2223
            ansible_user: root
      grafana:
        hosts:
          grafana:
            ansible_host: 127.0.0.1
            ansible_port: 22   # for SSH to grafana container
            ansible_user: root
  