all:
  children:

    monitored:
      hosts:
        host-a:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: root
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

        host-b:
          ansible_host: 127.0.0.1
          ansible_port: 2223
          ansible_user: root
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    grafana:
      hosts:
        grafana:
          ansible_host: 127.0.0.1
          ansible_port: 2224
          ansible_user: root
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  