all:
  hosts:
    host-a:
      ansible_connection: local
      output_dir: /tmp/host-a
    host-b:
      ansible_connection: local
      output_dir: /tmp/host-b
# all:
#   children:
#     monitored:
#       hosts:
#         host-a:
#           ansible_host: 127.0.0.1
#           ansible_port: 2222
#           ansible_user: root
#           ansible_ssh_private_key_file: ./ansible_key
#           ansible_ssh_common_args: "-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

#         host-b:
#           ansible_host: 127.0.0.1
#           ansible_port: 2223
#           ansible_user: root
#           ansible_ssh_private_key_file: ./ansible_key
#           ansible_ssh_common_args: "-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
