global:
  scrape_interval: 15s
  evaluation_interval: 15s

# federated alloy - each writes metrics to Prometheus
remote_write:
  - url: "http://prometheus:9090/api/v1/write"

scrape_configs:
  # Prometheus scrapes itself
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  # Prometheus scrapes Alloy on each host
  - job_name: 'alloy'
    static_configs:
      - targets:
          - 'host-a:12345'
          - 'host-b:12345'

rule_files:
  - "rules/*.yml"
