global:
  scrape_interval: 15s
  evaluation_interval: 15s

# federated alloy - each writes metrics to volume
remote_write:
  - url: "http://prometheus:9090/api/v1/write"

# Prometheus scrapes its own metrics
scrape_configs:
  - job_name: 'alloy'
    static_configs:
      - targets:
          - localhost:9090
