grafana_admin_user: admin
grafana_admin_password: admin
grafana_provisioning_path: /etc/grafana/provisioning
grafana_datasource_name: "monitored-hosts"
grafana_alloy_targets:
  - "host-a:12345"
  - "host-b:12345"
