alloy_version: "v1.5.0"
alloy_binary_url: "https://github.com/grafana/alloy/releases/download/{{ alloy_version }}/alloy-linux-amd64"
alloy_config_path: /etc/alloy/config.yaml
alloy_exporter_port: 12345

# Enable/disable exporters (future-proofing)
alloy_unix_exporter_enabled: true
alloy_process_exporter_enabled: true

prometheus_host: prometheus
prometheus_remote_write_port: 9090

# Full remote_write URL becomes:
# http://prometheus:9090/api/v1/write

# systemd
alloy_service_name: alloy
