- name: Ensure provisioning directory exists (if needed)
  file:
    path: "{{ grafana_provisioning_path }}"
    state: directory
    mode: "0755"

# If you need to tweak grafana.ini via template, do it here and notify restart

- name: Copy provisioning files
  copy:
    src: provisioning/
    dest: "{{ grafana_provisioning_path }}/"
    owner: root
    group: root
    mode: "0644"
  notify: restart grafana
